# Generated by Django 6.0.4 on 2026-06-04 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockhistory',
            old_name='new_stock',
            new_name='current_stock',
        ),
        migrations.RenameField(
            model_name='stockhistory',
            old_name='old_stock',
            new_name='previous_stock',
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='action',
            field=models.CharField(choices=[('IN', 'Stock Added'), ('OUT', 'Stock Sold')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product'),
        ),
    ]
