# Generated by Django 6.0.4 on 2026-06-04 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_new_stock_stockhistory_current_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='action',
            field=models.CharField(choices=[('IN', 'Stock Added'), ('OUT', 'Stock Removed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='backend.product'),
        ),
    ]
